version: '{branch}.{build}'
clone_depth: 1

environment:
  MSYSTEM: MINGW32

init:
  - git config --global core.autocrlf input

install:
  - set PATH=c:\msys64\mingw32\bin;c:\msys64\usr\bin;c:\msys64\bin;%PATH%
  - echo %PATH%
  - pacman -S --noconfirm --needed make ninja mingw-w64-i686-libusb mingw-w64-i686-sqlite3 mingw-w64-i686-zlib mingw-w64-i686-gcc

build_script:
  - make

artifacts:
  - path: fluxengine.exe
    name: fluxengine.exe

deploy:
  release: fluxengine-windows-client-v$(appveyor_build_version)
  description: FluxEngine Windows client
  provider: GitHub
  auth_token:
    secure: dfJjj7fWCoDUz+Ni11OcNPB/U3TNJFwNA2AsL++ChFjniUsZLlC6SDWHiL/t4FZo
  artifact: fluxengine.exe
  draft: false
  prerelease: false
  on:
    branch: master

