language: shell
git:
    depth: 1

matrix:
    include:
        -
            os: osx
            osx_image: xcode10.2
            compiler: clang
            env:
            - HOMEBREW_NO_INSTALL_CLEANUP=1

addons:
    homebrew:
        packages:
        - ninja

script:
- make


