language: generic

matrix:
    include:
        -
            os: linux
            sudo: false
            dist: xenial
            compiler: gcc
            env: CXX=g++-8
        -
            os: osx
            env: HOMEBREW_NO_AUTO_UPDATE=1
            compiler: clang

addons:
    apt:
        sources:
        - llvm-toolchain-precise-3.8
        - ubuntu-toolchain-r-test
        packages:
        - ninja-build
        - meson
        - libusb-1.0-0-dev
        - libsqlite3-dev
        - g++-8
    homebrew:
        packages:
        - ninja
        - meson

git:
    depth: 1

script:
    - make

