language: shell
git:
    depth: 1

matrix:
    include:
        -
            os: linux
            sudo: false
            dist: xenial
            compiler: gcc
            env: CXX=g++-8
            script:
              - make
        -
            os: osx
            osx_image: xcode10.2
            compiler: clang

addons:
    apt:
        sources:
        - llvm-toolchain-precise-3.8
        - ubuntu-toolchain-r-test
        packages:
        - ninja-build
        - libusb-1.0-0-dev
        - libsqlite3-dev
        - g++-8
    homebrew:
        packages:
        - ninja

script:
- make


