name: C/C++ CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: apt
      run: sudo apt install libusb-1.0-0-dev libsqlite3-dev ninja-build
    - name: make
      run: make

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: brew
      run: brew install sqlite pkg-config libusb ninja
    - name: make
      run: make

