name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: apt
      run: sudo apt install libusb-1.0-0-dev libsqlite3-dev ninja-build
    - name: make
      run: make

